### ISSUE TITLE
Page 15 of Git-GitHub.pptx

### ISSUE THREAD

**Issue by beutlich** [open-ideas/__CrashCourse__#12]
What you really miss on page 15 of the tutorial on TortoiseGit is the "new branch" checkbox at the top of the commit dialog.

![grafik](https://user-images.githubusercontent.com/14896695/40771987-1c327ac4-64bf-11e8-9720-2aec6ff8db02.png)

This way you can create new branches with your commit and easily push them later for filing a new PR on GitHub web.

Additionally, in the commit message, it is recommended to have a short explanation line of 50 (max 70 for nice GitHub rendering) characters, then an ampty line and afterwards a longer explanation.

**Comment by jelgerjansen** [comment]
This issue is outdated because we don't use TortoiseGit any more in the crash course and is therefore closed.
