### ISSUE TITLE
Update part on IDEAS.Types.Tilt in exercise 3

### ISSUE THREAD

**Issue by jelgerjansen** [open-ideas/__CrashCourse__#20]
On page 2 of exercise 3, something is set about predefined constants like `IDEAS.Types.Tilt.Wall`, `IDEAS.Types.Tilt.Floor`,...
However, the newest version of IDEAS has an additional parameters called `incOpt`  which automatically set the inclination depending on the type of outer wall. This should be updated in the exercise sheet.

The same analogy is applicable to the azimuth (`azi`) and corresponding parameter `aziOpt`.

**Comment by LoneMeertens** [comment]
The exercise sheet (latex and pdf) is updated, therefore this issue is closed.
