### ISSUE TITLE
Modelica by Example book has a new home

### ISSUE THREAD

**Issue by dietmarw** [open-ideas/__CrashCourse__#21]
I could not find the sources for the slides, so I file an isue instead of a PR here. 
On slide 12 of part 1-2 you link to http://book.xogeny.com/ but that page has now moved to https://mbe.modelica.university/

You migh also correct all `http://` links to `https://` links.

**Comment by lucasverleyen** [comment]
@dietmarw Thank you for your comment. We missed it last year, but we have updated all links in our slides for this year's edition!
